### PR TITLE
Add Python packages from the distribution

### PR DESCRIPTION
**Pull request by joshmoore**
* requests: for testing and adhoc scripts
 * yaml & jinja2: for plugin needs

### CODE REVIEW

**Comment by jburel** [comment]
Maybe I am missing something but in that case we should also update https://github.com/ome/omeroweb-install

**Comment by joshmoore** [comment]
Quite possibly. @aleksandra-tarkowska ?

**Comment by atarkowska** [comment]
yaml & jinja2 are OMERO.py deps not web, they are needed for populate metadata

**Comment by joshmoore** [comment]
So perhaps in the `apps` role then?

**Comment by atarkowska** [comment]
but metadata plugin is not an app yet? We can argue about the structure of packages and their dedicated roles more and more, as is chicken and egg problem. Would it be hard to rename this role to `ansible-role-omero-py-web-runtime` (renaming is always hard) ? Otherwise perhaps we need to stick with putting everything to one pot like in this PR

**Comment by joshmoore** [comment]
@manics suggests that with https://github.com/openmicroscopy/ansible-role-omero-web this repo is now deprecated. Closing this PR and migrating to https://github.com/openmicroscopy/ansible-role-omero-python-deps

**Pull request closed without merging**
