### PR TITLE
Deprecation: Update README

### PR DESCRIPTION
**Pull request by joshmoore**
Point users to:

 * https://github.com/openmicroscopy/ansible-role-omero-web and
 * https://github.com/openmicroscopy/ansible-role-omero-python-deps

### CODE REVIEW

**Comment by sbesson** [comment]
Makes sense. Worth updating `meta/main.yml` to include something along the lines of

```
  galaxy_tags:
   - deprecated
```

as well?

**Comment by kennethgillen** [comment]
Reads well.

**Comment by joshmoore** [comment]
Reactivating build after: "AttributeError: 'module' object has no attribute 'APIClient'"

**Comment by manics** [comment]
> Reactivating build after: "AttributeError: 'module' object has no attribute 'APIClient'"

Sounds like an incorrect combination of docker-python and molecule

**Comment by sbesson** [comment]
Works for me and ready to merge. To be thorough, should we also tag this as `0.1.1` to update the Ansible role with the deprecated tag?

**Comment by joshmoore** [comment]
I was thinking so. Doing now.

**Pull request merged**
